/**
 * SEC EDGAR data for Rungs 4-5. See PLAN.md section (h) for the design and
 * why this is a bundled snapshot rather than a live fetch (companyfacts has
 * no CORS; a static site cannot call it from the browser).
 *
 * The snapshot at `../data/edgar-snapshot.json` is generated by
 * `scripts/fetch-edgar.mjs`, an owner-run command — see `src/data/README.md`.
 */
import { extractFields, type XbrlCompanyFacts } from './edgar-extract'
import rawSnapshot from '../data/edgar-snapshot.json'

/** One company's extracted fields, as the game reads them. Every figure is `number | null` because tag coverage varies by filer. */
export interface EdgarCompany {
  ticker: string
  cik: string
  name: string
  fiscalYear: number | null
  periodEnd: string | null
  revenue: number | null
  ebit: number | null
  da: number | null
  netIncome: number | null
  cash: number | null
  shortTermInvestments: number | null
  debt: number | null
  shares: number | null
  totalAssets: number | null
  equity: number | null
  publicFloat: number | null
}

interface EdgarSnapshot {
  generatedAt: string
  companies: EdgarCompany[]
}

// TypeScript infers a JSON import's type from the literal file contents,
// which is more specific (and less stable across regenerations) than the
// shape we actually want. Assert through `unknown` to the hand-written
// `EdgarSnapshot` type instead, per PLAN.md section (h).
export const SNAPSHOT = rawSnapshot as unknown as EdgarSnapshot

/** All ten curated companies from the snapshot. */
export function edgarCompanies(): EdgarCompany[] {
  return SNAPSHOT.companies
}

/** Look up one company by ticker (case-insensitive). */
export function edgarByTicker(ticker: string): EdgarCompany | undefined {
  const needle = ticker.toUpperCase()
  return SNAPSHOT.companies.find((c) => c.ticker.toUpperCase() === needle)
}

/** EBIT + D&A. A proxy for EBITDA, not a reported GAAP figure — say so in the UI. Null if either input is missing. */
export function ebitda(c: Pick<EdgarCompany, 'ebit' | 'da'>): number | null {
  if (c.ebit === null || c.da === null) return null
  return c.ebit + c.da
}

/** Debt minus cash minus short-term investments. Null if debt or cash is not reported (short-term investments defaults to 0 when absent — most filers simply don't have the line). */
export function netDebt(c: Pick<EdgarCompany, 'debt' | 'cash' | 'shortTermInvestments'>): number | null {
  if (c.debt === null || c.cash === null) return null
  return c.debt - c.cash - (c.shortTermInvestments ?? 0)
}

/**
 * A rough stand-in for market capitalisation: `dei:EntityPublicFloat`, the
 * value of shares held by non-affiliates as of the cover-page date. It is
 * not "shares outstanding × current price" and can lag the market by
 * months — treat it as an anchor for the lesson, not a live quote.
 */
export function impliedMarketValue(c: Pick<EdgarCompany, 'publicFloat'>): number | null {
  return c.publicFloat
}

/** Enterprise value built from the public-float proxy: float + net debt. */
export function evFromFloat(c: Pick<EdgarCompany, 'publicFloat' | 'debt' | 'cash' | 'shortTermInvestments'>): number | null {
  const float = impliedMarketValue(c)
  const nd = netDebt(c)
  if (float === null || nd === null) return null
  return float + nd
}

/** EV / EBITDA using the float-based EV and the EBIT+D&A proxy. Null if either side is unavailable, or EBITDA is zero. */
export function evToEbitda(c: Pick<EdgarCompany, 'publicFloat' | 'debt' | 'cash' | 'shortTermInvestments' | 'ebit' | 'da'>): number | null {
  const ev = evFromFloat(c)
  const ebitdaValue = ebitda(c)
  if (ev === null || ebitdaValue === null || ebitdaValue === 0) return null
  return ev / ebitdaValue
}

/**
 * Format a dollar figure for display. `unit` picks the scale: `"$"` for a
 * plain comma-grouped dollar amount (the default), `"$M"` for millions,
 * `"$B"` for billions. Renders `"not reported"` for `null` rather than
 * `"$NaN"`.
 */
export function fmtMoney(n: number | null, unit: '$' | '$M' | '$B' = '$'): string {
  if (n === null) return 'not reported'
  if (unit === '$B') return `$${(n / 1e9).toFixed(1)}B`
  if (unit === '$M') return `$${(n / 1e6).toFixed(1)}M`
  return `$${Math.round(n).toLocaleString('en-US')}`
}

// ---------------------------------------------------------------------
// Live fetch path — currently blocked by CORS (verified against
// data.sec.gov: a plain GET returns 200 with no
// Access-Control-Allow-Origin header, and an OPTIONS preflight returns
// 403). Kept behind this function, not wired into any Settings toggle or
// screen, so that if SEC ever adds a CORS-friendly route the code is
// already here. UNUSED BY THE UI TODAY — the game reads SNAPSHOT above.
// ---------------------------------------------------------------------

/** The subset of a live company fetch we cache — the same ~15 fields as the snapshot, never the full companyfacts document (which can run several megabytes). */
export type LiveCompanyData = { cik: string; name: string | null } & ReturnType<typeof extractFields>

interface CacheEntry {
  fetchedAt: number
  ttlMs: number
  data: LiveCompanyData
}

const CACHE_TTL_MS = 7 * 24 * 60 * 60 * 1000

function cacheKey(cik: string): string {
  return `deal-desk:edgar:${cik}`
}

function readCache(storage: Pick<Storage, 'getItem'>, cik: string): LiveCompanyData | null {
  try {
    const raw = storage.getItem(cacheKey(cik))
    if (!raw) return null
    const entry = JSON.parse(raw) as CacheEntry
    if (Date.now() - entry.fetchedAt > entry.ttlMs) return null
    return entry.data
  } catch {
    return null
  }
}

function writeCache(storage: Pick<Storage, 'setItem'>, cik: string, data: LiveCompanyData): void {
  try {
    const entry: CacheEntry = { fetchedAt: Date.now(), ttlMs: CACHE_TTL_MS, data }
    storage.setItem(cacheKey(cik), JSON.stringify(entry))
  } catch {
    // Quota exceeded or storage unavailable; caching is best-effort only.
  }
}

/**
 * Fetch one company's facts directly from SEC EDGAR, bypassing the bundled
 * snapshot. Blocked by CORS in a browser today (see above) — exists so the
 * fallback plan in PLAN.md (h) has working code to switch to, not because
 * any screen calls it. Caches the extracted fields (not the raw document)
 * in `localStorage` under `deal-desk:edgar:<cik>` for 7 days.
 *
 * `storage` defaults to `localStorage` but accepts an override for tests.
 */
export async function fetchLiveCompany(
  cik: string,
  fetchImpl: typeof fetch = fetch,
  storage: Pick<Storage, 'getItem' | 'setItem'> = typeof localStorage === 'undefined' ? { getItem: () => null, setItem: () => {} } : localStorage,
): Promise<LiveCompanyData | null> {
  const padded = cik.padStart(10, '0')

  const cached = readCache(storage, padded)
  if (cached) return cached

  const res = await fetchImpl(`https://data.sec.gov/api/xbrl/companyfacts/CIK${padded}.json`)
  if (!res.ok) return null

  const doc = (await res.json()) as XbrlCompanyFacts
  const fields = extractFields(doc)
  const data: LiveCompanyData = { cik: padded, name: doc.entityName ?? null, ...fields }
  writeCache(storage, padded, data)
  return data
}
