// Generated character sprites for Deal Desk's pixel-art overworld.
// 16x20 chibi characters, bottom-centre anchored. See
// src/pixel/sprites/README.md for the authoring spec and src/pixel/palette.ts
// for the single shared colour legend ('.' is transparent).
//
// Each CharacterSet has three walk directions (down/up/left; right is
// mirrored by the render engine) with 3 frames [stand, walkA, walkB], plus a
// seated 'sit' pose with 2 frames [typingA, typingB] for desk scenes.

import type { Sprite } from '../sprite'

export interface CharacterSet {
  name: string
  down: Sprite
  up: Sprite
  left: Sprite
  sit: Sprite
}

const playerDown: Sprite = {
  name: 'player-down',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KnnnrrnnnK...',
      '...KnnnrrnnnK...',
      '...KNnnrrnnNK...',
      '...KsnnnnnnsK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '....KnnnnnnK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KnnnrrnnnK...',
      '...KnnnrrnnnK...',
      '...KNnnrrnnNK...',
      '...KnnnnnnnsK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '...KnnnnnnK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KnnnrrnnnK...',
      '...KnnnrrnnnK...',
      '...KNnnrrnnNK...',
      '...KsnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '.....KnnnnnnK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const playerUp: Sprite = {
  name: 'player-up',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KnnnnnnnnK...',
      '...KnnnnnnnnK...',
      '...KNnnnnnnNK...',
      '...KnnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '....KnnnnnnK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KssssK.....',
      '...KnnnnnnnnK...',
      '...KnnnnnnnnK...',
      '...KNnnnnnnNK...',
      '...KnnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '...KnnnnnnK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KssssK.....',
      '...KnnnnnnnnK...',
      '...KnnnnnnnnK...',
      '...KNnnnnnnNK...',
      '...KnnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '.....KnnnnnnK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const playerLeft: Sprite = {
  name: 'player-left',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KsssshhhhK...',
      '...KsssshhhhK...',
      '...KsKsshhhhK...',
      '...KsssshhhhK...',
      '....KssshhhK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KnnnnnnnnK...',
      '...KnnnnnnnnK...',
      '...KNnnnnnnNK...',
      '...KsnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '....KnnnnnnK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KsssshhhhK...',
      '...KsssshhhhK...',
      '...KsKsshhhhK...',
      '...KsssshhhhK...',
      '....KssshhhK....',
      '.....KssssK.....',
      '...KnnnnnnnnK...',
      '...KnnnnnnnnK...',
      '...KNnnnnnnNK...',
      '...KnnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '...KnnnnnnK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KsssshhhhK...',
      '...KsssshhhhK...',
      '...KsKsshhhhK...',
      '...KsssshhhhK...',
      '....KssshhhK....',
      '.....KssssK.....',
      '...KnnnnnnnnK...',
      '...KnnnnnnnnK...',
      '...KNnnnnnnNK...',
      '...KsnnnnnnnK...',
      '....KnnnnnnK....',
      '....KnnnnnnK....',
      '....KnnNNnnK....',
      '.....KnnnnnnK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const playerSit: Sprite = {
  name: 'player-sit',
  frameTicks: 14,
  frames: [
    [
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KnnnrrnnnK...',
      '...KnnnrrnnnK...',
      '...KNnnnnnnNK...',
      '...KnnnnnnnnK...',
      '...KsnnnnnnsK...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '.....KHHHHK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KnnnrrnnnK...',
      '...KnnnrrnnnK...',
      '...KNnnnnnnNK...',
      '...KsnnnnnnsK...',
      '....KnnnnnnK....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const PLAYER: CharacterSet = {
  name: 'The Intern',
  down: playerDown,
  up: playerUp,
  left: playerLeft,
  sit: playerSit,
}

const mdDown: Sprite = {
  name: 'md-down',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KossssssoK...',
      '...KsKssKsssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KKKKaaKKKK...',
      '...KKKKaaKKKK...',
      '...KkKKaaKKkK...',
      '...KsKKKKKKsK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KossssssoK...',
      '...KsKssKsssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KKKKaaKKKK...',
      '...KKKKaaKKKK...',
      '...KkKKaaKKkK...',
      '...KKKKKKKKsK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '...KKKKKKKK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KossssssoK...',
      '...KsKssKsssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KKKKaaKKKK...',
      '...KKKKaaKKKK...',
      '...KkKKaaKKkK...',
      '...KsKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '.....KKKKKKKK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const mdUp: Sprite = {
  name: 'md-up',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KooooooooK...',
      '...KooooooooK...',
      '...KooooooooK...',
      '...KooooooooK...',
      '....KooooooK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KkKKKKKKkK...',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KooooooooK...',
      '...KooooooooK...',
      '...KooooooooK...',
      '...KooooooooK...',
      '....KooooooK....',
      '.....KssssK.....',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KkKKKKKKkK...',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '...KKKKKKKK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KooooooooK...',
      '...KooooooooK...',
      '...KooooooooK...',
      '...KooooooooK...',
      '....KooooooK....',
      '.....KssssK.....',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KkKKKKKKkK...',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '.....KKKKKKKK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const mdLeft: Sprite = {
  name: 'md-left',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KssssooooK...',
      '...KKsssooooK...',
      '...KsKssooooK...',
      '...KssssooooK...',
      '....KsssoooK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KkKKKKKKkK...',
      '...KsKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KssssooooK...',
      '...KKsssooooK...',
      '...KsKssooooK...',
      '...KssssooooK...',
      '....KsssoooK....',
      '.....KssssK.....',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KkKKKKKKkK...',
      '...KKKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '...KKKKKKKK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KssssooooK...',
      '...KKsssooooK...',
      '...KsKssooooK...',
      '...KssssooooK...',
      '....KsssoooK....',
      '.....KssssK.....',
      '...KKKKKKKKKK...',
      '...KKKKKKKKKK...',
      '...KkKKKKKKkK...',
      '...KsKKKKKKKK...',
      '....KKKKKKKK....',
      '....KKKKKKKK....',
      '....KKKkkKKK....',
      '.....KKKKKKKK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const mdSit: Sprite = {
  name: 'md-sit',
  frameTicks: 14,
  frames: [
    [
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KossssssoK...',
      '...KsKssKsssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KKKKaaKKKK...',
      '...KKKKaaKKKK...',
      '...KkKKKKKKkK...',
      '...KKKKKKKKKK...',
      '...KsKKKKKKsK...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '.....KWWWWK.....',
      '....KooooooK....',
      '...KossssssoK...',
      '...KsKssKsssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KKKKaaKKKK...',
      '...KKKKaaKKKK...',
      '...KkKKKKKKkK...',
      '...KsKKKKKKsK...',
      '....KKKKKKKK....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const MD: CharacterSet = {
  name: 'The Managing Director',
  down: mdDown,
  up: mdUp,
  left: mdLeft,
  sit: mdSit,
}

const analystADown: Sprite = {
  name: 'analystA-down',
  frameTicks: 8,
  frames: [
    [
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssssssK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KttttK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KsttttttsK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssssssK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KtttttttsK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssssssK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KstttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const analystAUp: Sprite = {
  name: 'analystA-up',
  frameTicks: 8,
  frames: [
    [
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '....KyyyyyyK....',
      '.....KssssK.....',
      '.....KttttK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KttttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '....KyyyyyyK....',
      '.....KssssK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KttttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '...KyyyyyyyyK...',
      '....KyyyyyyK....',
      '.....KssssK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KttttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const analystALeft: Sprite = {
  name: 'analystA-left',
  frameTicks: 8,
  frames: [
    [
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssyyyyK...',
      '...KssssyyyyK...',
      '...KsKssyyyyK...',
      '...KssssyyyyK...',
      '....KsssyyyK....',
      '.....KssssK.....',
      '.....KttttK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KstttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssyyyyK...',
      '...KssssyyyyK...',
      '...KsKssyyyyK...',
      '...KssssyyyyK...',
      '....KsssyyyK....',
      '.....KssssK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KttttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssyyyyK...',
      '...KssssyyyyK...',
      '...KsKssyyyyK...',
      '...KssssyyyyK...',
      '....KsssyyyK....',
      '.....KssssK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KstttttttK...',
      '....KttttttK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const analystASit: Sprite = {
  name: 'analystA-sit',
  frameTicks: 14,
  frames: [
    [
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssssssK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KttttK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KttttttttK...',
      '...KsttttttsK...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '......KjjK......',
      '.....KjjjjK.....',
      '....KyyyyyyK....',
      '...KssssssssK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KttttK.....',
      '...KttttttttK...',
      '...KttttttttK...',
      '...KTttttttTK...',
      '...KsttttttsK...',
      '....KttttttK....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const ANALYST_A: CharacterSet = {
  name: 'Analyst',
  down: analystADown,
  up: analystAUp,
  left: analystALeft,
  sit: analystASit,
}

const analystBDown: Sprite = {
  name: 'analystB-down',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhbbbbbbhK...',
      '...KbbbbbbbbK...',
      '...KbKbbKbbbK...',
      '...KbbbbbbbbK...',
      '....KbbbbbbK....',
      '.....KbbbbK.....',
      '.....KWWWWK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KbqqqqqqbK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhbbbbbbhK...',
      '...KbbbbbbbbK...',
      '...KbKbbKbbbK...',
      '...KbbbbbbbbK...',
      '....KbbbbbbK....',
      '.....KbbbbK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KqqqqqqqbK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhbbbbbbhK...',
      '...KbbbbbbbbK...',
      '...KbKbbKbbbK...',
      '...KbbbbbbbbK...',
      '....KbbbbbbK....',
      '.....KbbbbK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KbqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const analystBUp: Sprite = {
  name: 'analystB-up',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KbbbbK.....',
      '.....KWWWWK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KqqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KbbbbK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KqqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KbbbbK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KqqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const analystBLeft: Sprite = {
  name: 'analystB-left',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KbbbbhhhhK...',
      '...KbbbbhhhhK...',
      '...KbKbbhhhhK...',
      '...KbbbbhhhhK...',
      '....KbbbhhhK....',
      '.....KbbbbK.....',
      '.....KWWWWK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KbqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KbbbbhhhhK...',
      '...KbbbbhhhhK...',
      '...KbKbbhhhhK...',
      '...KbbbbhhhhK...',
      '....KbbbhhhK....',
      '.....KbbbbK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KqqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KbbbbhhhhK...',
      '...KbbbbhhhhK...',
      '...KbKbbhhhhK...',
      '...KbbbbhhhhK...',
      '....KbbbhhhK....',
      '.....KbbbbK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KbqqqqqqqK...',
      '....KqqqqqqK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const analystBSit: Sprite = {
  name: 'analystB-sit',
  frameTicks: 14,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhbbbbbbhK...',
      '...KbbbbbbbbK...',
      '...KbKbbKbbbK...',
      '...KbbbbbbbbK...',
      '....KbbbbbbK....',
      '.....KbbbbK.....',
      '.....KWWWWK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KqqqqqqqqK...',
      '...KbqqqqqqbK...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhbbbbbbhK...',
      '...KbbbbbbbbK...',
      '...KbKbbKbbbK...',
      '...KbbbbbbbbK...',
      '....KbbbbbbK....',
      '.....KbbbbK.....',
      '.....KWWWWK.....',
      '...KqqqqqqqqK...',
      '...KqqqqqqqqK...',
      '...KQqqqqqqQK...',
      '...KbqqqqqqbK...',
      '....KqqqqqqK....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const ANALYST_B: CharacterSet = {
  name: 'Analyst',
  down: analystBDown,
  up: analystBUp,
  left: analystBLeft,
  sit: analystBSit,
}

const associateDown: Sprite = {
  name: 'associate-down',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KhsssshK....',
      '.....KssssK.....',
      '.....KrrrrK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KsrrrrrrsK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '....KssssssK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KhsssshK....',
      '.....KssssK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KrrrrrrrsK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '...KssssssK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KhsssshK....',
      '.....KssssK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KsrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '.....KssssssK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const associateUp: Sprite = {
  name: 'associate-up',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KssssK.....',
      '.....KrrrrK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KrrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '....KssssssK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KssssK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KrrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '...KssssssK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '...KhhhhhhhhK...',
      '....KhhhhhhK....',
      '.....KssssK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KrrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '.....KssssssK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const associateLeft: Sprite = {
  name: 'associate-left',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KsssshhhhK...',
      '...KsssshhhhK...',
      '...KsKsshhhhK...',
      '...KsssshhhhK...',
      '....KssshhhK....',
      '.....KssssK.....',
      '.....KrrrrK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KsrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '....KssssssK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KsssshhhhK...',
      '...KsssshhhhK...',
      '...KsKsshhhhK...',
      '...KsssshhhhK...',
      '....KssshhhK....',
      '.....KssssK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KrrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '...KssssssK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KsssshhhhK...',
      '...KsssshhhhK...',
      '...KsKsshhhhK...',
      '...KsssshhhhK...',
      '....KssshhhK....',
      '.....KssssK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KsrrrrrrrK...',
      '....KrrrrrrK....',
      '....KGGGGGGK....',
      '....KGGggGGK....',
      '.....KssssssK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const associateSit: Sprite = {
  name: 'associate-sit',
  frameTicks: 14,
  frames: [
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KhsssshK....',
      '.....KssssK.....',
      '.....KrrrrK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KrrrrrrrrK...',
      '...KsrrrrrrsK...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '.....KggggK.....',
      '....KhhhhhhK....',
      '...KhsssssshK...',
      '...KssssssssK...',
      '...KsKssKsssK...',
      '...KssssssssK...',
      '....KhsssshK....',
      '.....KssssK.....',
      '.....KrrrrK.....',
      '...KrrrrrrrrK...',
      '...KrrrrrrrrK...',
      '...KRrrrrrrRK...',
      '...KsrrrrrrsK...',
      '....KrrrrrrK....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const ASSOCIATE: CharacterSet = {
  name: 'The Associate',
  down: associateDown,
  up: associateUp,
  left: associateLeft,
  sit: associateSit,
}

const hrDown: Sprite = {
  name: 'hr-down',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRssssssRK...',
      '...KssssssssK...',
      '...KsKUKKUKsK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KsppppppsK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRssssssRK...',
      '...KssssssssK...',
      '...KsKUKKUKsK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KpppppppsK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRssssssRK...',
      '...KssssssssK...',
      '...KsKUKKUKsK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KspppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const hrUp: Sprite = {
  name: 'hr-up',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '....KRRRRRRK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KppppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '....KRRRRRRK....',
      '.....KssssK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KppppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '...KRRRRRRRRK...',
      '....KRRRRRRK....',
      '.....KssssK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KppppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const hrLeft: Sprite = {
  name: 'hr-left',
  frameTicks: 8,
  frames: [
    [
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KssssRRRRK...',
      '...KssssRRRRK...',
      '...KsKUsRRRRK...',
      '...KssssRRRRK...',
      '....KsssRRRK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KspppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '....KkkkkkkK....',
      '....KKKKKKKK....',
      '.....KKKKKK.....',
    ],
    [
      '................',
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KssssRRRRK...',
      '...KssssRRRRK...',
      '...KsKUsRRRRK...',
      '...KssssRRRRK...',
      '....KsssRRRK....',
      '.....KssssK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KppppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '...KkkkkkkK.....',
      '...KKKKKKKK.....',
      '....KKKKKK......',
    ],
    [
      '................',
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KssssRRRRK...',
      '...KssssRRRRK...',
      '...KsKUsRRRRK...',
      '...KssssRRRRK...',
      '....KsssRRRK....',
      '.....KssssK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KspppppppK...',
      '....KppppppK....',
      '....KkkkkkkK....',
      '....KkkKKkkK....',
      '.....KkkkkkkK...',
      '.....KKKKKKKK...',
      '......KKKKKK....',
    ],
  ],
}

const hrSit: Sprite = {
  name: 'hr-sit',
  frameTicks: 14,
  frames: [
    [
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRssssssRK...',
      '...KssssssssK...',
      '...KsKUKKUKsK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KppppppppK...',
      '...KsppppppsK...',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
    [
      '................',
      '.....KrrrrK.....',
      '....KRRRRRRK....',
      '...KRssssssRK...',
      '...KssssssssK...',
      '...KsKUKKUKsK...',
      '...KssssssssK...',
      '....KssssssK....',
      '.....KssssK.....',
      '.....KWWWWK.....',
      '...KppppppppK...',
      '...KppppppppK...',
      '...KrpppppprK...',
      '...KsppppppsK...',
      '....KppppppK....',
      '................',
      '................',
      '................',
      '................',
      '................',
    ],
  ],
}

export const HR: CharacterSet = {
  name: 'HR',
  down: hrDown,
  up: hrUp,
  left: hrLeft,
  sit: hrSit,
}


export const CHARACTERS: Record<string, CharacterSet> = {
  player: PLAYER,
  md: MD,
  analystA: ANALYST_A,
  analystB: ANALYST_B,
  associate: ASSOCIATE,
  hr: HR,
}
