import type { Sprite } from '../sprite'

export const ICON_COG: Sprite = {
  name: 'cog',
  frames: [
    [
      '.....KGGGGK.....',
      '...KKKGGGGKK....',
      '..KKGGGGGGGKK...',
      '.KKGGGGGGGGGKK..',
      '.KGGGGGGGGGGGK..',
      'KKGGGGGGGGGGGKKK',
      'GGGGGGKKKGGGGGGG',
      'GGGGGGK.KGGGGGGG',
      'GGGGGGKKKggggggg',
      'GGGGGGGGgggggKgg',
      'KKGGGGGGgggggKKK',
      '.KKGGGGGggggKK..',
      '..KKGGGGgggKK...',
      '...KKKGGgKKK....',
      '.....KGGggK.....',
      '.....KGGggK.....',
    ],
  ],
}

export const ICON_BACK: Sprite = {
  name: 'back',
  frames: [
    [
      '................',
      '........KKK.....',
      '.......KKWK.....',
      '.....KKKWWK.....',
      '....KKWWWWK.....',
      '..KKKWWWWWKKKKKK',
      '.KKWWWWWWWWWWWWK',
      '.KWWWWWWWWWWWWWK',
      '.KWWWWWWWWWWWWWK',
      '.KKWWWWWWWWWWWWK',
      '..KKKWWWWWKKKKKK',
      '....KKWWWWK.....',
      '.....KKKWWK.....',
      '.......KKKK.....',
      '................',
      '................',
    ],
  ],
}

export const ICON_LOCK: Sprite = {
  name: 'lock',
  frames: [
    [
      '...KKKKKKKKKK...',
      '...KaaaaaaaaK...',
      '...KaaaaaaaaK...',
      '...KaaaaaaaaK...',
      '...KaaKKKKaaK...',
      '...KaaK..KaaK...',
      '.KKKaaKKKKaaKKK.',
      '.KaaaaaaaAAAAAK.',
      '.KaaaaaaaAAAAAK.',
      '.KaaaaaKaAAAAAK.',
      '.KaaaaaKaAAAAAK.',
      '.KaaaaaKKAAAAAK.',
      '.KaaaaaKKAAAAAK.',
      '.KaaaaaaaAAAAAK.',
      '.KaaaaaaaAAAAAK.',
      '.KKKKKKKKKKKKKK.',
    ],
  ],
}

export const ICON_CHECK: Sprite = {
  name: 'check',
  frames: [
    [
      '................',
      '................',
      '............KKKK',
      '...........KKvvK',
      '..........KKvvKK',
      '.........KKvvKK.',
      '.........KvvKK..',
      '..KKKK..KKvvK...',
      '..KvvKKKKvvKK...',
      '..KvvvKKvvKK....',
      '..KKvvvvvKK.....',
      '...KKvvvKK......',
      '....KKvKK.......',
      '.....KKK........',
      '................',
      '................',
    ],
  ],
}

export const ICON_CROSS: Sprite = {
  name: 'cross',
  frames: [
    [
      '................',
      '................',
      '..KKKK.....KKKK.',
      '..KrrKK...KKrrK.',
      '..KrrrKK.KKrrKK.',
      '..KKrrrKKKrrKK..',
      '...KKrrrKrrKK...',
      '....KKrrrrKK....',
      '.....KKrrrKK....',
      '....KKrrrrrKK...',
      '...KKrrKKrrrKK..',
      '..KKrrKKKKrrrKK.',
      '..KrrKK..KKrrrK.',
      '..KrKK....KKrKK.',
      '..KKK......KKK..',
      '................',
    ],
  ],
}

export const ICON_MONEY_BAG: Sprite = {
  name: 'money-bag',
  frames: [
    [
      '................',
      '................',
      '.....KKKKKK.....',
      '....KKccccKK....',
      '....KCCCCCCK....',
      '..KKKCCCCCCKK...',
      '..KcccaaaCCCK...',
      '.KKcccaacCCCKK..',
      '.KcccccacCCCCK..',
      '.KcccccaaCCCCK..',
      '.KccccaaaCCCCK..',
      '.KcccccacCCCCK..',
      '.KKccccacCCCKK..',
      '..KccccccCCCK...',
      '..KKKccccCKKK...',
      '....KKKKKKK.....',
    ],
  ],
}

export const ICON_TROPHY: Sprite = {
  name: 'trophy',
  frames: [
    [
      '................',
      '.KKKKKKKKKKKKKK.',
      'KKaKaaaaaaAaKaKK',
      'KaKaaaaaaaAaaKaK',
      'KaKaaaaaaaAaaKaK',
      'KKaKaaaaaaAaKaKK',
      '.KKKKaaaaaAKKKK.',
      '....KaaaaaAK....',
      '....KKKaaKKK....',
      '......KaaK......',
      '....KKKaaKKK....',
      '....KaaaaaaK....',
      '...KKaaaaaaKK...',
      '...KAAAAAAAAK...',
      '...KKKKKKKKKK...',
      '................',
    ],
  ],
}

export const ICON_BRIEFCASE: Sprite = {
  name: 'briefcase',
  frames: [
    [
      '................',
      '................',
      '.....KKKKKK.....',
      '.....KCKKCK.....',
      '.....KCKKCK.....',
      '.KKKKKCKKCKKKKK.',
      '.KCCCCCCCCCCCCK.',
      '.KCCCCCCCCCCCCK.',
      '.KCCCCCaaCCCCCK.',
      '.KCCCCCaaCCCCCK.',
      '.KCCCCCCCCCCCCK.',
      '.KCCCCCCCCCCCCK.',
      '.KddddddddddddK.',
      '.KddddddddddddK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
  ],
}

export const ICON_COFFEE: Sprite = {
  name: 'coffee',
  frames: [
    [
      '....KKK.........',
      '....KiKKKK......',
      '....KiKKiK......',
      '....KKiKiKK.....',
      '.....KiKKiK.....',
      '.....KKKKiK.....',
      '..KKKKKKKKKK....',
      '..KWCCCCCCWKKKK.',
      '..KWCCCCCCWWWWK.',
      '..KWWWWWWWWWKWK.',
      '..KWWWWWWWWWKWK.',
      '..KWWWWWWWWWWWK.',
      '..KWWWWWWWWKKKK.',
      '..KKWWWWWWKK....',
      '...KKKKKKKK.....',
      '................',
    ],
  ],
}

export const ICON_CHART_UP: Sprite = {
  name: 'chart-up',
  frames: [
    [
      '................',
      '.KKK.......KKK..',
      '.KiK.......KvKKK',
      '.KiK......KKvvvK',
      '.KiK.....KKvvvvK',
      '.KiK....KKvKKKKK',
      '.KiK...KKvKK....',
      '.KiK..KKvKK.....',
      '.KiK.KKvKK......',
      '.KiKKKvKK.......',
      '.KiKvvKK........',
      '.KivKKK.........',
      '.KiKKKKKKKKKKKK.',
      '.KiiiiiiiiiiiiK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
  ],
}

export const ICON_CHART_DOWN: Sprite = {
  name: 'chart-down',
  frames: [
    [
      '................',
      '.KKK............',
      '.KiK............',
      '.KiKK...........',
      '.KirKKK.........',
      '.KiKrrKK........',
      '.KiKKKrKK.......',
      '.KiK.KKrKK......',
      '.KiK..KKrKKKKKK.',
      '.KiK...KKrrrrrK.',
      '.KiK....KKrrrrK.',
      '.KiK.....KKrrrK.',
      '.KiKKKKKKKKKrKK.',
      '.KiiiiiiiiiiiiK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
  ],
}

export const ICON_CLOCK: Sprite = {
  name: 'clock',
  frames: [
    [
      '......KKK.......',
      '...KKKKWKKKK....',
      '..KKWWWWWWWKK...',
      '.KKWWWWWKWWWKK..',
      '.KWWWWWWKWWWWK..',
      '.KWWWWWWKWWWWK..',
      'KKWWWWWWKWWWWKK.',
      'KWWWWWWKKWWWWWK.',
      'KKWWWWWWKKWWWKK.',
      '.KWWWWWWWWKKWK..',
      '.KWWWWWWWWWWWK..',
      '.KKWWWWWWWWWKK..',
      '..KKWWWWWWWKK...',
      '...KKKKWKKKK....',
      '......KKK.......',
      '................',
    ],
  ],
}

export const ICON_STAR: Sprite = {
  name: 'star',
  frames: [
    [
      '......KKKK......',
      '......KaaK......',
      '......KaaK......',
      '......KaaK......',
      '....KKKaaKKK....',
      '....KaaaaaaK....',
      'KKKKKaaaaaaKKKKK',
      'KaaaaaaaaaaaaaaK',
      'KaaaaaaaAAAaaaaK',
      'KKKKKaaaAAAKKKKK',
      '....KaaAAAAK....',
      '....KKKAAKKK....',
      '......KAAK......',
      '......KAAK......',
      '......KAAK......',
      '......KKKK......',
    ],
  ],
}

export const ICON_PHONE: Sprite = {
  name: 'phone',
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '..KKKKK..KKKKK..',
      '..KkkkKKKKkkkK..',
      '..KkkkkkkkkkkK..',
      '..KkkkkkkkkkkK..',
      '..KkkkkkkkkkkK..',
      '.KKKKKKKKKKKKKK.',
      '.KkkkkkkKkkkkkK.',
      '.KkkkkKkkKkkkkK.',
      '.KkkkkkkkkkkkkK.',
      '.KkkkkKkkKkkkkK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
  ],
}

export const ICON_ENVELOPE: Sprite = {
  name: 'envelope',
  frames: [
    [
      '................',
      '................',
      '................',
      '.KKKKKKKKKKKKKK.',
      '.KGGGGGGGGGGGGK.',
      '.KiGGGGGGGGGGiK.',
      '.KiiGGGGGGGGiiK.',
      '.KiiiGGGGGGiiiK.',
      '.KiiiiGGGGiiiiK.',
      '.KiiiiiiiiiiiiK.',
      '.KiiiiiiiiiiiiK.',
      '.KiiiiiiiiiiiiK.',
      '.KiiiiiiiiiiiiK.',
      '.KKKKKKKKKKKKKK.',
      '................',
      '................',
    ],
  ],
}

export const ICON_WARNING: Sprite = {
  name: 'warning',
  frames: [
    [
      '................',
      '.......KKK......',
      '......KKaKK.....',
      '......KaaAK.....',
      '.....KKaaaKK....',
      '.....KaKKaAK....',
      '....KKaKKaaKK...',
      '....KaaKKaaAK...',
      '...KKaaKKaaaKK..',
      '...KaaaKKaaaAK..',
      '..KKaaaaaaaaaKK.',
      '..KaaaaKKaaaaAK.',
      '..KaaaaKKaaaaaK.',
      '..KKKKKKKKKKKKK.',
      '................',
      '................',
    ],
  ],
}

export const ICON_GAVEL: Sprite = {
  name: 'gavel',
  frames: [
    [
      '................',
      '................',
      '.......KKKKKKKK.',
      '.......KCCCCCCK.',
      '.......KCCCCCCK.',
      '.......KCCCCCCK.',
      '.......KddddddK.',
      '.......KddddddK.',
      '......KKddKKKKK.',
      '.....KKddKK.....',
      '....KKddKK......',
      '...KKddKK.......',
      '..KKddKK........',
      '..KddKK.........',
      '..KdKK..........',
      '..KKK...........',
    ],
  ],
}

export const ICON_BUILDING: Sprite = {
  name: 'building',
  frames: [
    [
      '...KKKKKKKKKK...',
      '...KggggggGGK...',
      '...KggggggGGK...',
      '...KgjjgjjGGK...',
      '...KgjjgjjGGK...',
      '...KggggggGGK...',
      '...KgjjgjjGGK...',
      '...KgjjgjjGGK...',
      '...KggggggGGK...',
      '...KgjjgjjGGK...',
      '...KgjjgjjGGK...',
      '...KggggggGGK...',
      '...KgjjgjjGGK...',
      '...KgjjgjjGGK...',
      '...KggggggGGK...',
      '...KKKKKKKKKK...',
    ],
  ],
}

export const ICON_HEART: Sprite = {
  name: 'heart',
  frames: [
    [
      '................',
      '...KKKK.KKKK....',
      '..KKrrKKKrrKKK..',
      '.KKrrrrrrrrrrK..',
      '.KrrrrrrrrRrrK..',
      '.KrrrrrrrRRRrK..',
      '.KrrrrrrrRRRrKK.',
      '.KKrrrrrRRRRRRK.',
      '..KrrrrrRRRRRKK.',
      '..KKrrrrRRRRKK..',
      '...KKrrrRRRRK...',
      '....KrrrRRRKK...',
      '....KKrrRRKK....',
      '.....KKrRKK.....',
      '......KKKK......',
      '................',
    ],
  ],
}

export const ICON_TIE: Sprite = {
  name: 'tie',
  frames: [
    [
      '................',
      '.....KKKKKKK....',
      '.....KrrrrrK....',
      '.....KKrrrKK....',
      '.....KKrrrKK....',
      '.....KrrRrrK....',
      '.....KrrRrrK....',
      '.....KKrRrrK....',
      '......KrRrKK....',
      '......KrRrK.....',
      '......KrRrK.....',
      '......KKRrK.....',
      '.......KRKK.....',
      '.......KRK......',
      '.......KKK......',
      '................',
    ],
  ],
}

export const ICON_FAX: Sprite = {
  name: 'fax',
  frames: [
    [
      '................',
      '................',
      '...KKKKKKKKKK...',
      '...KIIIIIIIIK...',
      '.KKKIIIIIIIIKKK.',
      '.KGGIIIIIIIIGGK.',
      '.KGGGGGGGGGGGGK.',
      '.KGGGGGGGGGGGGK.',
      '.KGGGGGGGGGGGGK.',
      '.KGGIGIGIGGGGGK.',
      '.KGGGGGGGGGGGGK.',
      '.KIIIIIIIIIIIIK.',
      '.KIIIIIIIIIIIIK.',
      '.KIIIIIIIIIIIIK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
  ],
}

export const ICON_DOC: Sprite = {
  name: 'doc',
  frames: [
    [
      '................',
      '..KKKKKKKKKKKK..',
      '..KWWWWWWiiiiK..',
      '..KWWWWWWWiiiK..',
      '..KWWWWWWWWiiK..',
      '..KWWWWWWWWWWK..',
      '..KWWkkkkkkWWK..',
      '..KWWWWWWWWWWK..',
      '..KWWkkkkkkWWK..',
      '..KWWWWWWWWWWK..',
      '..KWWkkkkkkWWK..',
      '..KWWWWWWWWWWK..',
      '..KWWWWWWWWWWK..',
      '..KWWWWWWWWWWK..',
      '..KKKKKKKKKKKK..',
      '................',
    ],
  ],
}

export const ICON_CALC: Sprite = {
  name: 'calc',
  frames: [
    [
      '................',
      '.KKKKKKKKKKKKKK.',
      '.KkkkkkkkkkkkkK.',
      '.KkkkkkkkkkkkkK.',
      '.KkkjjjjjjjjkkK.',
      '.KkkjjjjjjjjkkK.',
      '.KkkjjjjjjjjkkK.',
      '.KkkkkkkkkkkkkK.',
      '.KkkGkkGkkGkkkK.',
      '.KkkkkkkkkkkkkK.',
      '.KkkGkkGkkGkkkK.',
      '.KkkkkkkkkkkkkK.',
      '.KkkGkkGkkGkkkK.',
      '.KkkkkkkkkkkkkK.',
      '.KKKKKKKKKKKKKK.',
      '................',
    ],
  ],
}

export const ICON_HANDSHAKE: Sprite = {
  name: 'handshake',
  frames: [
    [
      '................',
      '................',
      '................',
      '................',
      '................',
      '......KKK.......',
      '.....KKSKK......',
      '....KKSSSKKK....',
      '....KSSSSSsKK...',
      '....KKSSSsssKK..',
      '...KKssSKKsssK..',
      '..KKssKKKKKssKK.',
      '.KKssKK...KsssKK',
      '.KssKK....KKsssK',
      '.KsKK......KKsKK',
      '.KKK........KKK.',
    ],
  ],
}

export const ICON_KEY: Sprite = {
  name: 'key',
  frames: [
    [
      '...KKK..........',
      '.KKKaKKK........',
      '.KaaaaaK........',
      'KKaaKaaKK.......',
      'KaaKKKaaK.......',
      'KKaaKaaKKK......',
      '.KaaaaaaAK......',
      '.KKKaKaaAK......',
      '...KKKaaAK......',
      '.....KaaAKKK....',
      '.....KaaAaaK....',
      '.....KaaAaaKK...',
      '.....KaaAaaaK...',
      '.....KaaAaaaK...',
      '.....KKKKKKKK...',
      '................',
    ],
  ],
}

export const ICON_SOUND_ON: Sprite = {
  name: 'sound-on',
  frames: [
    [
      '................',
      '................',
      '....KKK.........',
      '....KWKK........',
      '....KWWKK..KKK..',
      '.KKKKWWWKKKKUK..',
      '.KWWWWWWWKKUKKK.',
      '.KWWWWWWWWKKKUK.',
      '.KWWWWWWWWKKKUK.',
      '.KWWWWWWWKKUKKK.',
      '.KKKKWWWKKKKUK..',
      '....KWWKK..KKK..',
      '....KKKK........',
      '................',
      '................',
      '................',
    ],
  ],
}

export const ICON_SOUND_OFF: Sprite = {
  name: 'sound-off',
  frames: [
    [
      '................',
      '................',
      '....KKK.........',
      '....KWKK........',
      '....KWWKK.KKKKKK',
      '.KKKKWWWKKKrKKrK',
      '.KWWWWWWWKKKrrKK',
      '.KWWWWWWWWKKrrKK',
      '.KWWWWWWWWKrKKrK',
      '.KWWWWWWWKKKKKKK',
      '.KKKKWWWKK......',
      '....KWWKK.......',
      '....KKKK........',
      '................',
      '................',
      '................',
    ],
  ],
}

export const ICON_SHARE: Sprite = {
  name: 'share',
  frames: [
    [
      '................',
      '................',
      '........KKKKKKK.',
      '........KuuuuuK.',
      '........KKuuuuK.',
      '.........KKuuuK.',
      '.KKKKKKKKKuKuuK.',
      '.KuuuuuuuuKKKKK.',
      '.KuKKKKKuuK.....',
      '.KuK..KuKuK.....',
      '.KuK..KKKuK.....',
      '.KuK....KuK.....',
      '.KuKKKKKKuK.....',
      '.KuuuuuuuuK.....',
      '.KKKKKKKKKK.....',
      '................',
    ],
  ],
}

export const ICON_DOWNLOAD: Sprite = {
  name: 'download',
  frames: [
    [
      '................',
      '......KKKK......',
      '......KuuK......',
      '......KuuK......',
      '......KuuK......',
      '......KuuK......',
      '......KuuK......',
      '...KKKKuuKKKK...',
      '...KuuuuuuuuK...',
      '...KKuuuuuuKK...',
      '....KKuuuuKK....',
      '.....KKuuKK.....',
      '.KKKKKKKKKKKKKK.',
      '.KuuuuuuuuuuuuK.',
      '.KuuuuuuuuuuuuK.',
      '.KKKKKKKKKKKKKK.',
    ],
  ],
}

export const ICON_UPLOAD: Sprite = {
  name: 'upload',
  frames: [
    [
      '................',
      '.......KKK......',
      '......KKuK......',
      '.....KKuuKK.....',
      '....KKuuuuKK....',
      '....KuuuuuuK....',
      '....KKKuuKKK....',
      '......KuuK......',
      '......KuuK......',
      '......KuuK......',
      '......KuuK......',
      '......KuuK......',
      '.KKKKKKuuKKKKKK.',
      '.KuuuuuuuuuuuuK.',
      '.KuuuuuuuuuuuuK.',
      '.KKKKKKKKKKKKKK.',
    ],
  ],
}

export const ICON_TRASH: Sprite = {
  name: 'trash',
  frames: [
    [
      '.....KKKKKK.....',
      '.....KggggK.....',
      '..KKKKggggKKKK..',
      '..KggggggggggK..',
      '..KggggggggggK..',
      '..KKggggggggKK..',
      '...KggIggIggK...',
      '...KggIggIggK...',
      '...KggIggIggK...',
      '...KggIggIggK...',
      '...KggIggIggK...',
      '...KggIggIggK...',
      '...KggIggIggK...',
      '...KggggggggK...',
      '...KKKKKKKKKK...',
      '................',
    ],
  ],
}

export const ICON_SKULL: Sprite = {
  name: 'skull',
  frames: [
    [
      '....KKKKKKK.....',
      '...KKWWWWWKK....',
      '..KKWWWWWWWKK...',
      '..KWWWWWWWWWK...',
      '..KWWWWWWWWWK...',
      '..KWWKKWWKKWK...',
      '..KWWKKWWKKWK...',
      '..KWWKKWWKKWK...',
      '..KWWWWKKWWWK...',
      '..KKWWWWWWWWK...',
      '...KWWWWWWWWK...',
      '...KWWKWWKWWK...',
      '...KWWWWWWWWK...',
      '...KKKKKKKKKK...',
      '................',
      '................',
    ],
  ],
}

export const ICON_FIRE: Sprite = {
  name: 'fire',
  frames: [
    [
      '.......KKK......',
      '......KKOK......',
      '......KOOK......',
      '.....KKOOKK.....',
      '.....KOOaOK.....',
      '....KKOaaOKK....',
      '....KOOaaOOK....',
      '...KKOOarOOKK...',
      '...KOOarraOOK...',
      '..KKOOarraOOKK..',
      '..KOOOarraOOOK..',
      '..KKOaarrraKKK..',
      '...KOOrrrrOK....',
      '...KOOOOOOOK....',
      '...KKKOOOKKK....',
      '.....KKKKK......',
    ],
  ],
}

export const ICON_BOSS: Sprite = {
  name: 'boss',
  frames: [
    [
      '.......KKK......',
      '.......KaK......',
      '...KKK.KaK.KKK..',
      '...KaK.KaK.KaK..',
      '...KaK.KAKKKaK..',
      '...KaKKKaaKKaKK.',
      '..KKAaKaaaKKAaK.',
      '..KaaaKaaaKaaaK.',
      '..KaaaKaaaKaaaK.',
      '..KaaaaaaaaaaKK.',
      '..KaaaaaaaaaaK..',
      '..KAAAAAAAAAAK..',
      '..KAAAAAAAAAAK..',
      '..KKKKKKKKKKKK..',
      '................',
      '................',
    ],
  ],
}

export const ICON_MENTOR: Sprite = {
  name: 'mentor',
  frames: [
    [
      '................',
      '......KKKK......',
      '....KKKqQKKK....',
      '..KKKqqqqQQKKK..',
      'KKKqqqqqqqQQQKKK',
      'KqqqqqqqqqqQQQQK',
      'KKKqqqqqqqQQQKKK',
      '..KKKqqqqQQKKK..',
      '....KqqqqqqQK...',
      '....KqqqqqqQK...',
      '....KqqqqqqQK...',
      '....KKKKKKKQK...',
      '..........KQK...',
      '..........KQK...',
      '..........KKK...',
      '................',
    ],
  ],
}

export const ICON_COIN: Sprite = {
  name: 'coin',
  frames: [
    [
      '......KKK.......',
      '...KKKKaKKKK....',
      '..KKaaaaAAAKK...',
      '.KKaaaaaAAAAKK..',
      '.KaaajjaAAAAAK..',
      '.KaaajaaAAAAAK..',
      'KKaaaaaaAAAAAKK.',
      'KaaaaaaaAAAAAAK.',
      'KKaaaaaaAAAAAKK.',
      '.KaaaaaaAAAAAK..',
      '.KaaaaaaAAAAAK..',
      '.KKaaaaaAAAAKK..',
      '..KKaaaaAAAKK...',
      '...KKKKaKKKK....',
      '......KKK.......',
      '................',
    ],
    [
      '.....KKKKK......',
      '....KKaaAKK.....',
      '...KKaaaAAKK....',
      '...KaaaaAAAK....',
      '...KaajaAAAK....',
      '...KaajaAAAK....',
      '..KKaaaaAAAKK...',
      '..KaaaaaAAAAK...',
      '..KKaaaaAAAKK...',
      '...KaaaaAAAK....',
      '...KaaaaAAAK....',
      '...KaaaaAAAK....',
      '...KKaaaAAKK....',
      '....KKaaAKK.....',
      '.....KKKKK......',
      '................',
    ],
    [
      '.....KKKKKK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KAjAAK.....',
      '.....KKKKKK.....',
    ],
    [
      '.....KKKKK......',
      '....KKAAaKK.....',
      '...KKAAAaaKK....',
      '...KAAAAaaaK....',
      '...KAAAAajaK....',
      '...KAAAAajaK....',
      '..KKAAAAaaaKK...',
      '..KAAAAAaaaaK...',
      '..KKAAAAaaaKK...',
      '...KAAAAaaaK....',
      '...KAAAAaaaK....',
      '...KAAAAaaaK....',
      '...KKAAAaaKK....',
      '....KKAAaKK.....',
      '.....KKKKK......',
      '................',
    ],
  ],
  frameTicks: 6,
}

export const ICON_HOURGLASS: Sprite = {
  name: 'hourglass',
  frames: [
    [
      '..KKKKKKKKKKKK..',
      '..KCCCCCCCCCCK..',
      '..KCCCCCCCCCCK..',
      '..KKiiiiiiiiKK..',
      '...KKaaaaaaKK...',
      '....KKaaaaKK....',
      '.....KiaaiK.....',
      '.....KKaaKK.....',
      '.....KKiiKK.....',
      '.....KiiiiK.....',
      '....KKiiiiKK....',
      '....KiiiiiiK....',
      '..KKKKKKKKKKKK..',
      '..KCCCCCCCCCCK..',
      '..KCCCCCCCCCCK..',
      '..KKKKKKKKKKKK..',
    ],
    [
      '..KKKKKKKKKKKK..',
      '..KCCCCCCCCCCK..',
      '..KCCCCCCCCCCK..',
      '..KKiiiiiiiiKK..',
      '...KKiiiiiiKK...',
      '....KKiiiiKK....',
      '.....KiaiiK.....',
      '.....KKiiKK.....',
      '.....KKiaKK.....',
      '.....KiaaiK.....',
      '....KKaaaaKK....',
      '....KiiiiiiK....',
      '..KKKKKKKKKKKK..',
      '..KCCCCCCCCCCK..',
      '..KCCCCCCCCCCK..',
      '..KKKKKKKKKKKK..',
    ],
  ],
  frameTicks: 30,
}

export const EMBLEM_BONUS: Sprite = {
  name: 'emblem-bonus',
  frames: [
    [
      '................................',
      '............KKKKKKKK............',
      '.........KKKKWWWWWWKKKK.........',
      '.........KaKKWWWWWWKKjK.........',
      '.........KKKKWWWWWWKKKK.........',
      '............KWWWWWWK.KKK........',
      '........KKK.KWWWWWWK.KaK........',
      '........KjK.KKvvvvKK.KKK........',
      '........KKK..KvvvvK.............',
      '.............KvvvvK.............',
      '.............KvvvvK.............',
      '.............KvvvvK.............',
      '.............KvvvvK.............',
      '...........KKKvvvvKKK...........',
      '...........KvvvvvvVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '.........KKKvvvvvVVVKKK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KKKKKKKKKKKKKK.........',
      '................................',
    ],
    [
      '..........KKK...................',
      '..........KjKKKKKKKK............',
      '..........KKKWWWWWWK..KKK.......',
      '............KWWWWWWK..KjK.......',
      '.......KKK..KWWWWWWK..KKK.......',
      '.......KaK..KWWWWWWK............',
      '.......KKK..KWWWWWWK............',
      '............KKvvvvKKKK..........',
      '.............KvvvvKKaK..........',
      '.............KvvvvKKKK..........',
      '.............KvvvvK.............',
      '.............KvvvvK.............',
      '.............KvvvvK.............',
      '...........KKKvvvvKKK...........',
      '...........KvvvvvvVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '...........KvvvvvVVVK...........',
      '.........KKKvvvvvVVVKKK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KVVVVVVVVVVVVK.........',
      '.........KKKKKKKKKKKKKK.........',
      '................................',
    ],
  ],
  frameTicks: 10,
}

export const EMBLEM_REVIEW: Sprite = {
  name: 'emblem-review',
  frames: [
    [
      '...........KKKKKKKKKK...........',
      '...........KIIIIIIIIK...........',
      '.....KKKKKKKIIIIIIIIKKKKKKK.....',
      '.....KGGGGGGIIIIIIIIGGGIIIK.....',
      '.....KGGGGGGIIIIIIIIGGGIIIK.....',
      '.....KGGGGGGIIIIIIIIGGGIIIK.....',
      '.....KGGGGGGGGGGGGGGGGGIIIK.....',
      '.....KGGGWWWWWWWWWWWWWWIIIK.....',
      '.....KGGGWWWWWWWWWWWWWWIIIK.....',
      '.....KGGGWrrrWWWWWWWWrrrIIK.....',
      '.....KGGGWrrrrWWWWWWrrrIIIK.....',
      '.....KGGGWrrrrWWWWWWrrrIIIK.....',
      '.....KGGGWWrrrrWWWWrrrWIIIK.....',
      '.....KGGGWWrrrrrWWrrrWWIIIK.....',
      '.....KGGGWWWrrrrrrrrWWWIIIK.....',
      '.....KGGGWWWWrrrrrrrWWWIIIK.....',
      '.....KGGGWWWWWrrrrrWWWWIIIK.....',
      '.....KGGGWWWWWrrrrrWWWWIIIK.....',
      '.....KGGGWWWWWrrrrrrWWWIIIK.....',
      '.....KGGGWWWWWrrrrrrWWWIIIK.....',
      '.....KGGGWWWWrrrWrrrrWWIIIK.....',
      '.....KGGGWWWrrrWWrrrrrWIIIK.....',
      '.....KGGGWWrrrWWWWrrrrrIIIK.....',
      '.....KGGGWWrrrWWWWWrrrrIIIK.....',
      '.....KGGGWrrrWWWWWWWrrrrIIK.....',
      '.....KGGGWrrWWWWWWWWrrWIIIK.....',
      '.....KGGGWrWWWWWWWWWWrWIIIK.....',
      '.....KIIIIIIIIIIIIIIIIIIIIK.....',
      '.....KIIIIIIIIIIIIIIIIIIIIK.....',
      '.....KIIIIIIIIIIIIIIIIIIIIK.....',
      '.....KKKKKKKKKKKKKKKKKKKKKK.....',
      '................................',
    ],
  ],
}

export const EMBLEM_PROMOTION: Sprite = {
  name: 'emblem-promotion',
  frames: [
    [
      '................................',
      '................................',
      '...........KKKKKKKKK............',
      '.........KKKaaaaaaaKKK..........',
      '........KKaaaaaaaaaaaKK.........',
      '.......KKaaaaaaaaaaaaaKK........',
      '......KKaaaaaaWWWWaaaaaKK.......',
      '......KaaaaaaaWWWWaaaaaaK.......',
      '.....KKaaaaaaaWWWWaaaaaaKK......',
      '.....KaaaaaaaaWWWWaaaaaaaK......',
      '.....KaaaaaaaaWWWWaaaaaaaK......',
      '.....KaaWWWWWWWWWWWWWWWWaK......',
      '.....KaaWWWWWWWWWWWWWWWWaK......',
      '.....KaaWWWWWWWWWWWWWWWWAK......',
      '.....KaaWWWWWWWWWWWWWWWWAK......',
      '.....KaaaaaaaaWWWWAAAAAAAK......',
      '.....KaaaaaaaaWWWWAAAAAAAK......',
      '.....KKaaaaaaaWWWWAAAAAAKK......',
      '......KaaaaaaaWWWWAAAAAAK.......',
      '......KKaaaaaaWWWWAAAAAKK.......',
      '.......KKaAaaaWWWWaaaAKK........',
      '........KKAaaaaaAaaaaAK.........',
      '........KKAaaaaaAaaaaAKK........',
      '........KaAaaaKKKKaaaAaK........',
      '........KaAaaKK..KKaaAaK........',
      '........KaAaaK....KKaAaK........',
      '........KaAaKK.....KaAaK........',
      '.......KKaAKK......KKAaKK.......',
      '.......KaaAK........KAaaK.......',
      '.......KaaAK........KAaaK.......',
      '.......KKKKK........KKKKK.......',
      '................................',
    ],
  ],
}

export const EMBLEM_BOSS: Sprite = {
  name: 'emblem-boss',
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
      '...KkkkkkkkkkkkkkkkkkkkkkkkkK...',
      '...KkkkkkkkkkkkAAkkkkkkkkkkkK...',
      '...KkkkkkkkkkKAAAArkkkkkkkkkK...',
      '...KkkkkkkkkkKAAAArkkkkkkkkkK...',
      '...KkkkkkkkkkKKAArKkkkkkkkkkK...',
      '...KkkkkkkkkkKKrrrKkkkkkkkkkK...',
      '...KkkkkkkkkkKKKrKKkkkkkkkkkK...',
      '...KKKKKkkkkkKKrrRKkkkkkKKKKK...',
      '.......KkkkkkKKrrRKkkkkkK.......',
      '.......KkkkkkKkrrRKkkkkkK.......',
      '.......KkkkkkkkrrRkkkkkkK.......',
      '.......KkkkkkkkrrRkkkkkkK.......',
      '.......KkkkkkkkrrRkkkkkkK.......',
      '.......KkkkkkkkkrRkkkkkkK.......',
      '.......KkkkkkkkkrRkkkkkkK.......',
      '.......KkkkkkkkkrRkkkkkkK.......',
      '.......KkkkkkkkkrRkkkkkkK.......',
      '.......KkkkkkkkkrRkkkkkkK.......',
      '.......KkkkkkkkkkRkkkkkkK.......',
      '.......KkkkkkkkkkkkkkkkkK.......',
      '.......KkkkkkkkkkkkkkkkkK.......',
      '.......KkkkkkkkkkkkkkkkkK.......',
      '.......KKKKKKKKKKKKKKKKKK.......',
      '................................',
    ],
  ],
}

export const EMBLEM_INTERVIEW: Sprite = {
  name: 'emblem-interview',
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '...KKKKKKKKKKKKKKKK.............',
      '..KKWWWWWWWWWWWWWWKK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KWWWWWWWWWWWWWWWWK............',
      '..KKWWWWWWWWWWWWWWKK............',
      '...KKKWWWWKKKKKKKKKKKKKKKKKKKK..',
      '....KKWWWKK..KKUUUUUUUUUUUUUUKK.',
      '....KWWWKK...KUUUUUUUUUUUUUUUUK.',
      '....KWWKK....KUUUUUUUUUUUUUUUUK.',
      '....KKKK.....KUUUUUUUUUUUUUUUUK.',
      '.............KUUUUUUUUUUUUUUUUK.',
      '.............KUUUUUUUUUUUUUUUUK.',
      '.............KUUUUUUUUUUUUUUUUK.',
      '.............KUUUUUUUUUUUUUUUUK.',
      '.............KUUUUUUUUUUUUUUUUK.',
      '.............KUUUUUUUUUUUUUUUUK.',
      '.............KKUUUUUUUUUUUUUUKK.',
      '..............KKKKKKKKKUUUUKKK..',
      '......................KKKUUUK...',
      '........................KKUUK...',
      '.........................KKKK...',
    ],
  ],
}

export const EMBLEM_DEAL: Sprite = {
  name: 'emblem-deal',
  frames: [
    [
      '................................',
      '................................',
      '.....................KKKKK......',
      '..................KKKKCddK......',
      '...............KKKKCCCCCKK......',
      '............KKKKCCCCCCKKK.......',
      '.........KKKKCCCCCCKKKK.........',
      '.......KKKCCCCCCKKKK............',
      '.......KCCCCCKKKK...............',
      '.......KCCKKKKKKKKKK............',
      '.......KKKK.KaaaaaaK............',
      '...KKKKKKKKKKaaaaaaKKKKKKKKK....',
      '..KKiiiiiiiiiaaaaaaiiiiiiiiKK...',
      '.KKiiiiiiiiiiaaaaaaiiiiiiiiiKK..',
      '.KiiiiiiiiiiiaaaaaaiiiiiiiiiiK..',
      '.KiiiiiiiiiiAAAAAAAAiiiiiiiiiK..',
      '.KiiiiiiiiiiAAAAAAAAiiiiiiiiiK..',
      '.KiiiiiiiiiiAAAAAAAAiiiiiiiiiK..',
      '.KKiiiiiiiiiiaaaaaaiiiiiiiiiKK..',
      '..KKiiiiiiiiiaaaaaaiiiiiiiiKK...',
      '...KKKiiiiiiiaaaaaaiiiiiiiKK....',
      '.....KKKKKKKKaaaaaaKKKKKKKK.....',
      '............KaaaaaaK............',
      '............KKKKKKKK............',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
    ],
  ],
}

export const EMBLEM_SENT: Sprite = {
  name: 'emblem-sent',
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '.........KKKKKKKKKKKKKK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.......KKKjjjjjjjjjjjjKKK.......',
      '.......KIIjjjjjjjjjjjjIIK.......',
      '.......KIIjjjjjjjjjjjjIIK.......',
      '...KKKKKIIIIIIIIIIIIIIIIKKKKK...',
      '...KGGGGIIIIIIIIIIIIIIIIGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
      '................................',
    ],
    [
      '.........KKKKKKKKKKKKKK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.........KjjjjjjjjjjjjK.........',
      '.......KKKjjjjjjjjjjjjKKK.......',
      '.......KIIjjjjjjjjjjjjIIK.......',
      '.......KIIjjjjjjjjjjjjIIK.......',
      '...KKKKKIIIIIIIIIIIIIIIIKKKKK...',
      '...KGGGGIIIIIIIIIIIIIIIIGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KGGGGGGGGGGGGGGGGGGGGGGGGK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KIIIIIIIIIIIIIIIIIIIIIIIIK...',
      '...KKKKKKKKKKKKKKKKKKKKKKKKKK...',
      '................................',
    ],
  ],
  frameTicks: 12,
}

export const EMBLEM_LOCKED: Sprite = {
  name: 'emblem-locked',
  frames: [
    [
      '................................',
      '........KKKKKK.....KKKKKK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '........KaaaaK.....KaaaaK.......',
      '....KKKKKaaaaKKKKKKKaaaaKKKKK...',
      '....KaaaaaaaaaaaaaaAAAAAAAAAK...',
      '....KaaaaaaaaaaaaaaAAAAAAAAAK...',
      '....KaaaaaaaaaKKKKaAAAAAAAAAK...',
      '....KaaaaaaaaKKKKKKAAAAAAAAAK...',
      '....KaaaaaaaaKKKKKKAAAAAAAAAK...',
      '....KaaaaaaaaKKKKKKAAAAAAAAAK...',
      '....KaaaaaaaaKKKKKKAAAAAAAAAK...',
      '....KaaaaaaaaaKKKKaAAAAAAAAAK...',
      '....KaaaaaaaaaaKKKaAAAAAAAAAK...',
      '....KaaaaaaaaaaKKKaAAAAAAAAAK...',
      '....KaaaaaaaaaaKKKaAAAAAAAAAK...',
      '....KaaaaaaaaaaKKKaAAAAAAAAAK...',
      '....KaaaaaaaaaaaaaaAAAAAAAAAK...',
      '....KaaaaaaaaaaaaaaAAAAAAAAAK...',
      '....KaaaaaaaaaaaaaaAAAAAAAAAK...',
      '....KKKKKKKKKKKKKKKKKKKKKKKKK...',
      '................................',
      '................................',
    ],
  ],
}

export const EMBLEM_CASH: Sprite = {
  name: 'emblem-cash',
  frames: [
    [
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '................................',
      '........KKKKKKKKKKKKKKKKKKKKKKKK',
      '........KvvvvvvvvvvvvvvvvvvvvvvK',
      '........KvvvvvvvvvvvvvvvvvvvvvvK',
      '........KvvvvvvvvvvvvvvvvvvvvvvK',
      '........KWWWWWWWWWWWWWWWWWWWWWWK',
      '.....KKKKWWWWWWWWWWWWWWWWWWWWWWK',
      '.....KvvvWWWWWWWWWWWWWWWWWWWWWWK',
      '.....KvvvvvvvvvvvvvvvvvvvvvvvvvK',
      '.....KvvvVVVVVVVVVVVVVVVVVVVVVVK',
      '.....KvvvVVVVVVVVVVVVVVVVVVVVVVK',
      '..KKKKvvvVVVVVVVVVVVVVVVVVVVVVVK',
      '..KvvvvvvvvvvvvvvvvvvvvvvvvvKKKK',
      '..KvvvvvvvvvvvvvvvvvvvvvvvvvK...',
      '..KvvvVVVVVVVVVVVVVVVVVVVVVVK...',
      '..KWWWWWWWWWWWWWWWWWWWWWWVVVK...',
      '..KWWWWWWWWWWWWWWWWWWWWWWVVVK...',
      '..KWWWWWWWWWWWWWWWWWWWWWWKKKK...',
      '..KvvvvvvvvvvvvvvvvvvvvvvK......',
      '..KVVVVVVVVVVVVVVVVVVVVVVK......',
      '..KVVVVVVVVVVVVVVVVVVVVVVK......',
      '..KVVVVVVVVVVVVVVVVVVVVVVK......',
      '..KKKKKKKKKKKKKKKKKKKKKKKK......',
      '................................',
      '................................',
      '................................',
    ],
  ],
}

export const DEAL_DESK_LOGO: Sprite = {
  name: 'deal-desk-logo',
  frames: [
    [
      '................................................................',
      '................................................................',
      '................................................................',
      '.......KKKKKKKKKKKKKKKKKKKKK.....KKKKKKKKKKKKKKKKKKKKK.KKK......',
      '.......KWWWWKKWWWWWKKWWWKKWK.....KvvvvKKvvvvvKKvvvvKvKKKvK......',
      '.......KWKKKWKWKKKKKWKKKWKWK.....KvKKKvKvKKKKKvKKKKKvKKvKK......',
      '.......KWK.KWKWWWWKKWKKKWKWK.....KvK.KvKvvvvKKvKKKKKvKvKK.......',
      '.......KWK.KWKWKKKKKWWWWWKWK.....KvK.KvKvKKKKKKvvvKKvvKK........',
      '.......KWK.KWKWK...KWKKKWKWK.....KvK.KvKvK....KKKKvKvKvKK.......',
      '.......KWKKKWKWKKKKKWK.KWKWKKKKK.KvKKKvKvKKKKKKKKKvKvKKvKK......',
      '.......KWWWWKKWWWWWKWK.KWKWWWWWK.KvvvvKKvvvvvKvvvvKKvKKKvK......',
      '.......KKKKKKKKKKKKKKK.KKKKKKKKK.KKKKKKKKKKKKKKKKKKKKK.KKK......',
      '................................................................',
      '................................................................',
      '................................................................',
      '................................................................',
    ],
  ],
}

export const ICONS: Record<string, Sprite> = {
  iconCog: ICON_COG,
  iconBack: ICON_BACK,
  iconLock: ICON_LOCK,
  iconCheck: ICON_CHECK,
  iconCross: ICON_CROSS,
  iconMoneyBag: ICON_MONEY_BAG,
  iconTrophy: ICON_TROPHY,
  iconBriefcase: ICON_BRIEFCASE,
  iconCoffee: ICON_COFFEE,
  iconChartUp: ICON_CHART_UP,
  iconChartDown: ICON_CHART_DOWN,
  iconClock: ICON_CLOCK,
  iconStar: ICON_STAR,
  iconPhone: ICON_PHONE,
  iconEnvelope: ICON_ENVELOPE,
  iconWarning: ICON_WARNING,
  iconGavel: ICON_GAVEL,
  iconBuilding: ICON_BUILDING,
  iconHeart: ICON_HEART,
  iconTie: ICON_TIE,
  iconFax: ICON_FAX,
  iconDoc: ICON_DOC,
  iconCalc: ICON_CALC,
  iconHandshake: ICON_HANDSHAKE,
  iconKey: ICON_KEY,
  iconSoundOn: ICON_SOUND_ON,
  iconSoundOff: ICON_SOUND_OFF,
  iconShare: ICON_SHARE,
  iconDownload: ICON_DOWNLOAD,
  iconUpload: ICON_UPLOAD,
  iconTrash: ICON_TRASH,
  iconSkull: ICON_SKULL,
  iconFire: ICON_FIRE,
  iconBoss: ICON_BOSS,
  iconMentor: ICON_MENTOR,
  iconCoin: ICON_COIN,
  iconHourglass: ICON_HOURGLASS,
  emblemBonus: EMBLEM_BONUS,
  emblemReview: EMBLEM_REVIEW,
  emblemPromotion: EMBLEM_PROMOTION,
  emblemBoss: EMBLEM_BOSS,
  emblemInterview: EMBLEM_INTERVIEW,
  emblemDeal: EMBLEM_DEAL,
  emblemSent: EMBLEM_SENT,
  emblemLocked: EMBLEM_LOCKED,
  emblemCash: EMBLEM_CASH,
  dealDeskLogo: DEAL_DESK_LOGO,
}

