import type { Mission } from '../engine/types'
import { gradeWaterfall } from '../engine/graders/waterfall'
import { mdVerdict } from '../engine/voice'
import { LEDGERLY } from './companies'

const { revenue, cogs, grossProfit, sga, rnd, gna, da, ebit, ebitda, interest, taxes, netIncome } = LEDGERLY.income

/**
 * Rung 2, mission 1. Ledgerly Inc.'s income statement as a waterfall, built
 * down to EBITDA and beyond. Figures come from the Rung 2 company bible
 * (fiscal year 2025); see src/missions/companies.ts.
 */
const mission: Mission = {
  id: 'r2-waterfall-ebitda',
  rung: 2,
  order: 1,
  title: 'Build the waterfall',
  tagline: 'Revenue walks downhill until only cash-ish profit is left.',
  baseComp: 6_000,
  parSeconds: 150,
  lesson: {
    title: 'EBITDA: profit before the boring parts',
    body:
      'EBITDA stands for Earnings Before Interest, Taxes, Depreciation, and Amortisation — profit before financing costs, the tax bill, and the accounting charge for aging equipment (depreciation) or intangible assets (amortisation). Bankers like it because it strips out choices that differ company to company, like how much debt a company carries or which tax rate it pays, leaving something closer to cash generated by the actual business. That is also its flaw: EBITDA still ignores real cash spent on interest, taxes, and new equipment, so a company can show a healthy EBITDA while quietly burning cash. Never mistake it for actual profit.',
    visual: {
      kind: 'bullets',
      items: [
        'Revenue minus cost of revenue = gross profit',
        'Gross profit minus operating costs = EBITDA',
        'EBITDA minus D&A = EBIT (operating profit)',
        'EBIT minus interest and taxes = net income',
      ],
    },
  },
  task: {
    kind: 'waterfall',
    prompt: "Build Ledgerly's income statement, one bar at a time.",
    unit: '$k',
    tolerance: 0,
    steps: [
      { id: 'revenue', label: 'Revenue', role: 'revenue', value: revenue, total: true },
      { id: 'cost-of-revenue', label: 'Cost of revenue', role: 'cost', value: -cogs },
      { id: 'gross-profit', label: 'Gross profit', role: 'revenue', answer: grossProfit, total: true },
      { id: 'sales-marketing', label: 'Sales & marketing', role: 'cost', value: -(sga ?? 0) },
      { id: 'research-development', label: 'Research & development', role: 'cost', value: -(rnd ?? 0) },
      { id: 'general-admin', label: 'General & administrative', role: 'cost', value: -(gna ?? 0) },
      { id: 'ebitda', label: 'EBITDA', role: 'revenue', answer: ebitda, total: true },
      { id: 'depreciation-amortisation', label: 'Depreciation & amortisation', role: 'cost', value: -(da ?? 0) },
      { id: 'ebit', label: 'Operating profit (EBIT)', role: 'revenue', answer: ebit, total: true },
      { id: 'interest-expense', label: 'Interest expense', role: 'debt', value: -interest },
      { id: 'taxes', label: 'Taxes', role: 'cost', value: -taxes },
      { id: 'net-income', label: 'Net income', role: 'equity', answer: netIncome, total: true },
    ],
  },
  grade(answer) {
    if (answer.kind !== 'waterfall') throw new Error('wrong answer kind')
    if (mission.task.kind !== 'waterfall') throw new Error('wrong task kind')
    return gradeWaterfall(mission.task, answer, ({ accuracy, wrongIds }) => {
      const verdict = mdVerdict(accuracy, 'r2-waterfall-ebitda')
      if (accuracy === 1) {
        return {
          verdict,
          explanation:
            `Gross profit is revenue minus cost of revenue: ${revenue.toLocaleString()} − ${cogs.toLocaleString()} = ${grossProfit.toLocaleString()}. ` +
            `EBITDA is gross profit minus the operating costs above the line, before financing, taxes, and depreciation touch it: ${grossProfit.toLocaleString()} − ${sga?.toLocaleString()} (sales & marketing) − ${rnd?.toLocaleString()} (R&D) − ${gna?.toLocaleString()} (G&A) = ${ebitda.toLocaleString()}. ` +
            `Operating profit (EBIT) is EBITDA minus depreciation & amortisation: ${ebitda.toLocaleString()} − ${da?.toLocaleString()} = ${ebit.toLocaleString()}. ` +
            `Net income is EBIT minus interest and taxes: ${ebit.toLocaleString()} − ${interest.toLocaleString()} − ${taxes.toLocaleString()} = ${netIncome.toLocaleString()}.`,
        }
      }
      if (accuracy === 0) {
        return {
          verdict,
          explanation:
            `Nothing lined up. Gross profit is revenue minus cost of revenue: ${revenue.toLocaleString()} − ${cogs.toLocaleString()} = ${grossProfit.toLocaleString()}. ` +
            `EBITDA is gross profit minus sales & marketing, R&D, and G&A: ${grossProfit.toLocaleString()} − ${sga?.toLocaleString()} − ${rnd?.toLocaleString()} − ${gna?.toLocaleString()} = ${ebitda.toLocaleString()}. ` +
            `EBIT is EBITDA minus depreciation & amortisation: ${ebitda.toLocaleString()} − ${da?.toLocaleString()} = ${ebit.toLocaleString()}. ` +
            `Net income is EBIT minus interest and taxes: ${ebit.toLocaleString()} − ${interest.toLocaleString()} − ${taxes.toLocaleString()} = ${netIncome.toLocaleString()}.`,
        }
      }
      const hints: string[] = []
      if (wrongIds.includes('gross-profit'))
        hints.push(
          `Gross profit is revenue minus cost of revenue (what it cost to deliver the software, mostly hosting and support): ${revenue.toLocaleString()} − ${cogs.toLocaleString()} = ${grossProfit.toLocaleString()}.`,
        )
      if (wrongIds.includes('ebitda'))
        hints.push(
          `EBITDA is gross profit minus sales & marketing, research & development, and general & administrative costs, the operating expenses that sit above financing and depreciation: ${grossProfit.toLocaleString()} − ${sga?.toLocaleString()} − ${rnd?.toLocaleString()} − ${gna?.toLocaleString()} = ${ebitda.toLocaleString()}.`,
        )
      if (wrongIds.includes('ebit'))
        hints.push(
          `Operating profit (EBIT) is EBITDA minus depreciation & amortisation, the accounting charge for aging equipment and intangible assets: ${ebitda.toLocaleString()} − ${da?.toLocaleString()} = ${ebit.toLocaleString()}.`,
        )
      if (wrongIds.includes('net-income'))
        hints.push(
          `Net income is EBIT minus interest expense (the cost of Ledgerly's debt) and taxes: ${ebit.toLocaleString()} − ${interest.toLocaleString()} − ${taxes.toLocaleString()} = ${netIncome.toLocaleString()}.`,
        )
      hints.push('Each blank is the line above it minus the costs listed between them.')
      return { verdict, explanation: hints.join(' ') }
    })
  },
}

export default mission
